"""Generate an auditor-readable evidence pack from a chain-verified ledger.

    python scripts/evidence_pack.py --from 2026-07-01 --to 2026-07-16 \
        [--framework eu-ai-act|soc2|hipaa|all] [--redact REGEX ...] \
        [--out PATH] [--root ROOT]

The pack maps date-ranged, integrity-chained receipts to the record-keeping
language of common frameworks: control <-> receipt <-> chain proof. It
REFUSES to generate from a ledger whose chain audit is RED - evidence that
cannot prove it was not edited is not evidence.

NOT LEGAL ADVICE. The pack is supporting evidence prepared by the operator;
it is not a certification and does not by itself establish compliance with
any framework. Have qualified counsel or your auditor assess sufficiency.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from showwork.audit import audit_root  # noqa: E402
from showwork.checks import evaluate_records  # noqa: E402
from showwork.ledger import ledger_dir, resolve_root  # noqa: E402

FRAMEWORKS: dict[str, dict] = {
    "eu-ai-act": {
        "title": "EU AI Act (Regulation (EU) 2024/1689)",
        "controls": [
            ("Art. 12 - Record-keeping",
             "High-risk AI systems must technically allow the automatic "
             "recording of events (logs) over the system's lifetime.",
             "Every agent session appends session lifecycle events and "
             "falsifiable claims to an append-only JSONL ledger at the moment "
             "of assertion; nothing here was reconstructed after the fact."),
            ("Art. 26(6) - Deployer log retention",
             "Deployers of high-risk AI systems keep the logs automatically "
             "generated by the system, to the extent under their control, "
             "for a period appropriate to the intended purpose.",
             "This pack exports the retained ledger for the stated date "
             "range; the integrity chain proves retention without "
             "modification since each record was written."),
        ],
    },
    "soc2": {
        "title": "SOC 2 (AICPA Trust Services Criteria)",
        "controls": [
            ("CC8.1 - Change management",
             "The entity authorizes, designs, develops, tests, approves, and "
             "implements changes to meet its objectives.",
             "Agent-executed changes carry falsifiable claims verified "
             "deterministically against the repository; the exit gate refuses "
             "unverified 'done' states, and refusals are durable records."),
            ("CC7.2 / CC7.3 - System monitoring and event evaluation",
             "The entity monitors system components for anomalies and "
             "evaluates security events.",
             "Stop-hook verdicts, refused closes, and retractions constitute "
             "recorded anomalies in agent behavior, with timestamps and "
             "session attribution."),
        ],
    },
    "hipaa": {
        "title": "HIPAA Security Rule (45 CFR Part 164)",
        "controls": [
            ("164.312(b) - Audit controls",
             "Implement hardware, software, and/or procedural mechanisms "
             "that record and examine activity in information systems.",
             "The ledger records agent activity as structured, verifiable "
             "claims; `showwork verify` and `showwork audit` are the "
             "examination mechanisms, both deterministic."),
            ("164.316(b) - Documentation retention",
             "Retain required documentation for six years from creation or "
             "last effective date.",
             "Append-only files with a per-record hash chain; the chain "
             "audit in this pack demonstrates the export equals what was "
             "originally recorded."),
        ],
    },
}

DISCLAIMER = (
    "> **Scope and status.** This bundle is supporting evidence prepared by "
    "the system operator. It is NOT legal advice, NOT a certification, and "
    "does NOT by itself establish compliance with any framework. Control "
    "mappings describe what the ledger demonstrates; sufficiency is a "
    "determination for your auditor or counsel.")


def _read_jsonl(path: Path) -> list[dict]:
    if not path.is_file():
        return []
    out = []
    for line in path.read_text(encoding="utf-8-sig").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            out.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return out


def _in_range(ts: str, lo: str, hi: str) -> bool:
    day = str(ts)[:10]
    return lo <= day <= hi


def build_pack(root: Path, date_from: str, date_to: str, frameworks: list[str],
               redact: list[str]) -> tuple[int, str]:
    chain = audit_root(root)
    if chain["verdict"] == "RED":
        return 2, ("REFUSED: the ledger's integrity chain is RED. Evidence "
                   "that cannot prove it was not edited is not evidence.\n"
                   + json.dumps(chain, indent=2))

    def scrub(text: str) -> str:
        for pattern in redact:
            text = re.sub(pattern, "[redacted]", text)
        return text

    claims: list[dict] = []
    for p in sorted(ledger_dir(root).glob("claims-*.jsonl")):
        claims.extend(r for r in _read_jsonl(p) if _in_range(r.get("ts", ""), date_from, date_to))
    events = [e for e in _read_jsonl(ledger_dir(root) / "sessions.jsonl")
              if _in_range(e.get("ts", ""), date_from, date_to)]

    state = evaluate_records(claims, root, label=f"{date_from}..{date_to}")
    sessions = sorted({str(e.get("session")) for e in events if e.get("session")})
    refused = [e for e in events if e.get("event") == "session.finish.refused"]
    bypassed = [e for e in events if e.get("event") == "session.finish" and e.get("verify_bypassed")]

    now = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    lines = [
        f"# Evidence pack - agent activity receipts {date_from} .. {date_to}",
        "",
        f"Generated {now} by showwork `evidence_pack.py` from the ledger at "
        f"`{ledger_dir(root).name}/`.",
        "",
        DISCLAIMER,
        "",
        "## 1. Integrity of this evidence",
        "",
        f"Chain audit verdict at export time: **{chain['verdict']}** "
        f"({chain['total_chained']}/{chain['total_records']} records chained).",
        "",
        "| ledger file | records | chained | pre-chain | head (SHA-256, first 16) |",
        "|---|---:|---:|---:|---|",
    ]
    for f in chain["files"]:
        head = (f["head"] or "")[:16]
        lines.append(f"| {f['file']} | {f['records']} | {f['chained']} "
                     f"| {f['pre_chain']} | `{head}` |")
    lines += [
        "",
        "Any party holding this pack can re-audit: `showwork audit` on the "
        "ledger must reproduce these heads. A single altered byte anywhere "
        "in chained history changes a head.",
        "",
        "## 2. Activity summary",
        "",
        f"- Sessions active in range: **{len(sessions)}**",
        f"- Claims recorded in range: **{len(claims)}** "
        f"({state['passed']}/{state['total']} verify at export time; "
        f"verdict {state['verdict']})",
        f"- Exit-gate refusals in range: **{len(refused)}** "
        "(a refusal is the gate catching an unverified 'done')",
        f"- Verification bypasses in range: **{len(bypassed)}**",
        "",
        "## 3. Control mapping",
        "",
    ]
    for key in frameworks:
        fw = FRAMEWORKS[key]
        lines.append(f"### {fw['title']}")
        lines.append("")
        lines.append("| control | requirement (paraphrased) | what this ledger demonstrates |")
        lines.append("|---|---|---|")
        for control, req, demo in fw["controls"]:
            lines.append(f"| {control} | {req} | {demo} |")
        lines.append("")
    lines += [
        "## 4. Receipt inventory",
        "",
        "| ts | session | claim | check | verifies now |",
        "|---|---|---|---|---|",
    ]
    mark = {"pass": "OK", "fail": "XX", "error": "!!", "skipped": ".."}
    for rec, res in zip(
            [c for c in claims
             if not (c.get("retracted") and isinstance(c.get("retracts"), dict))],
            state["results"]):
        ctype = (rec.get("check") or {}).get("type", "-")
        lines.append(f"| {rec.get('ts', '')} | {scrub(str(rec.get('session', '')))} "
                     f"| {scrub(str(rec.get('claim', '')))} | `{ctype}` "
                     f"| {mark.get(res['status'], '??')} |")
    lines += [
        "",
        "Retraction records and refused closes remain in the ledger verbatim; "
        "they are part of the evidence, not blemishes to remove.",
        "",
    ]
    return 0, "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Generate a compliance evidence pack from the ledger")
    ap.add_argument("--root", default=None)
    ap.add_argument("--from", dest="date_from", required=True)
    ap.add_argument("--to", dest="date_to", required=True)
    ap.add_argument("--framework", default="all",
                    choices=[*FRAMEWORKS.keys(), "all"])
    ap.add_argument("--redact", action="append", default=[],
                    help="regex to mask in rendered session/claim text (repeatable)")
    ap.add_argument("--out", default=None, help="write the pack here (default: stdout)")
    args = ap.parse_args(argv)

    frameworks = list(FRAMEWORKS) if args.framework == "all" else [args.framework]
    code, text = build_pack(resolve_root(args.root), args.date_from,
                            args.date_to, frameworks, args.redact)
    if args.out and code == 0:
        Path(args.out).write_text(text, encoding="utf-8")
        print(f"evidence pack written: {args.out}")
    else:
        print(text)
    return code


if __name__ == "__main__":
    raise SystemExit(main())
